- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract Node Exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/opt/"
    remote_src: yes

- name: Move Node Exporter binary
  copy:
    src: "/opt/node_exporter-1.4.0.linux-amd64/"
    dest: "/etc/node_exporter/"
    remote_src: yes

- name: Create Node Exporter service file
  copy:
    dest: "/etc/systemd/system/node_exporter.service"
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=root
      ExecStart=/etc/node_exporter/node_exporter
      Restart=always

      [Install]
      WantedBy=default.target
  notify: Restart Node Exporter

- name: Enable and start Node Exporter service
  systemd:
    name: node_exporter
    enabled: yes
    state: started
