- name: Install and configure Prometheus & Grafana
  hosts: monitoring
  become: yes
  roles:
    - prometheus_grafana

- name: Install and configure Node Exporter on Linux servers
  hosts: linux_servers
  become: yes
  roles:
    - node_exporter
